# Generated by Django 6.0 on 2025-12-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_alter_bookrequest_user_alter_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("librarian", "Librarian")],
                default="student",
                max_length=20,
            ),
        ),
    ]
