# Generated by Django 6.0 on 2025-12-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
