# Generated by Django 4.2.7 on 2026-04-02 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0007_transaction_status_alter_book_author_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('AVAILABLE', 'Available'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='WAITING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='portal.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
