# Generated by Django 4.2.7 on 2026-04-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_bookreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_read_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reading_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
