# Generated by Django 4.2.29 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_interlibraryloanrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="eresource",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="eresources/"),
        ),
    ]

