# Generated by Django 6.0 on 2025-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eresource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
                ("letter", models.CharField(max_length=1)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="barcode",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
