from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('books/', views.book_list, name='book_list'),
    path('books/<int:book_id>/', views.book_detail, name='book_detail'),
    path('my-books/', views.my_books, name='my_books'),
    path('student-dashboard/', views.student_dashboard, name='student_dashboard'),
    path('librarian-dashboard/', views.librarian_dashboard, name='librarian_dashboard'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('request-book/<int:book_id>/', views.request_book, name='request_book'),
    path('issue-book/', views.issue_book, name='issue_book'),
    path('return-book/<int:tx_id>/', views.return_book, name='return_book'),
    path('export-transactions-csv/', views.export_transactions_csv, name='export_transactions_csv'),
    path('export-transactions-pdf/', views.export_transactions_pdf, name='export_transactions_pdf'),
    path('search-suggestions/', views.search_suggestions, name='search_suggestions'),
    path('search/', views.search_view, name='search'),
    path('advanced-search/', views.advanced_search_view, name='advanced_search'),
    path('my-requests/', views.my_requests, name='my_requests'),
    path('manage-requests/', views.manage_requests, name='manage_requests'),
    path('eresources/<str:letter>/', views.eresource_list_view, name='eresource_list'),
    path('contact/', views.contact, name='contact'),
    path('opening-hours/', views.opening_hours, name='opening_hours'),
    path('ask-librarian/', views.ask_librarian, name='ask_librarian'),
    path('book-study-room/', views.book_study_room, name='book_study_room'),
    path('news/', views.news, name='news'),
    path('departments/', views.department_list, name='department_list'),
    path('departments/<int:dept_id>/books/', views.department_books, name='department_books'),
    path('trending-books/', views.trending_books, name='trending_books'),
    path('new-arrivals/', views.new_arrivals, name='new_arrivals'),
    path('rare-books/', views.rare_books, name='rare_books'),
    path('theses-dissertations/', views.theses_dissertations, name='theses_dissertations'),
    path('anu-archives/', views.anu_archives, name='anu_archives'),

    # API Endpoints
    path('api/dashboard/stats/', views.dashboard_stats, name='dashboard_stats'),
    path('api/department-issues/', views.department_issues_api, name='department_issues_api'),
    path('api/monthly-trends/', views.monthly_trends_api, name='monthly_trends_api'),
    path('api/most-issued-books/', views.most_issued_books_api, name='most_issued_books_api'),
    path('api/overdue-books/', views.overdue_books_api, name='overdue_books_api'),
    path('api/low-stock-books/', views.low_stock_books_api, name='low_stock_books_api'),
    path('api/student-issued/', views.student_issued_api, name='student_issued_api'),
    path('api/student-history/', views.student_history_api, name='student_history_api'),
]
